### ISSUE TITLE
Use specific version of pg_dump/pg_restore

### ISSUE THREAD

**Issue by zedalaye** [Scalingo/scalingo_databases_rake_tasks-gem#4]
I have PG 9.3, 9.4 and 9.5 installed on my development box. When I try to backup a remote database using this gem, I get this error:
````
pg_dump: version du serveur : 9.4.5 ; pg_dump version : 9.3.10
pg_dump: annulation à cause de la différence des versions
````
Maybe we could try to pass the ```--cluster 9.4/main``` option to ```pg_dump``` and ```pg_restore``` according to the version running on Scalingo ?

**Comment by whollacsek** [comment]
Hi @zedalaye, with the next version (0.1.4) you'll be able to specify the tools you want to use with `PG_DUMP_CMD` and `PG_RESTORE_CMD`
